// Autogenerated configuration header
#pragma once

#ifndef GEODE_THREAD_SAFE
#define GEODE_THREAD_SAFE 1
#endif

#ifndef GEODE_GMP
#define GEODE_GMP
#endif

#ifndef BOOST_EXCEPTION_DISABLE
#define BOOST_EXCEPTION_DISABLE
#endif

#include <geode/python/config.h>
#include <geode/utility/config.h>